### ISSUE TITLE
[BUG?] Install FAILS in Odoo 14 community edition

### ISSUE THREAD

**Issue by c3kkos** [OCA/hr-holidays#52]
Installation of hr_holidays_public fails in "odooApp 14.0-20220727"

Module affected:
hr_holidays_public
version: 14.0.13.0.3.0.6

this is a custom docker-compose image, taken from the official pulled image (odoo:14)

traceback:

`Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1754, in run
    result = action.run()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions.py", line 632, in run
    res = runner(run_self, eval_context=eval_context)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions.py", line 501, in _run_action_code_multi
    safe_eval(self.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/usr/lib/python3/dist-packages/odoo/tools/safe_eval.py", line 346, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: <class 'odoo.tools.convert.ParseError'>: "while parsing /mnt/extra-addons/hr_holidays_public/views/hr_leave_type.xml:7, near
<record id="edit_holiday_status_form" model="ir.ui.view">
        <field name="name">hr.leave.type.form</field>
        <field name="model">hr.leave.type</field>
        <field name="inherit_id" ref="hr_holidays.edit_holiday_status_form"/>
        <field name="arch" type="xml">
            <xpath expr="//group[@name='visibility']" position="after">
                <group name="public_holidays" string="Public Holidays">
                    <field name="exclude_public_holidays"/>
                </group>
            </xpath>
        </field>
    </record>" while evaluating
'records.button_immediate_install()'`

i have no ideas....

**Comment by pedrobaeza** [comment]
This is something of your specific DB, as it installs correctly in a fresh one. Please try on a fresh DB.

Closing as this doesn't depend on the module.
